version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://admin:shalom***@mysql/blog_db
#    depends_on:
#      - mysql
#      - nginx
    restart: unless-stopped

#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root***
#      MYSQL_DATABASE: blog_db
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: shalom***
#    volumes:
#      - mysql_data:var/lib/mysql
#      - ./migrations:/docker-entrypoint-initdb.d
#    ports:
#      - "3306:3306"
#    restart: unless-stopped
#    healthcheck:
#      test: [CMD, "mysqladmin", "ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 10
#
#  nginx:
#    image: nginx:1.23
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./static:/var/www/static
#    depends_on:
#      - app
#    restart: unless-stopped
#
#volumes:
#  mysql_data: